name: 'Import Google Apps Script Versions to Git'
description: 'Imports Google Apps Script versions to a Git repository.'
branding:
  icon: 'git-commit'
  color: 'blue'

inputs:
  script_id:
    description: 'Google Apps Script ID'
    required: true
  author_name:
    description: 'Commit author name (optional)'
    required: false
    default: ''
  author_email:
    description: 'Commit author email (optional)'
    required: false
    default: ''
  CLASP_REFRESH_TOKEN:
    description: 'The refresh token for clasp.'
    required: true
  CLASP_CLIENT_ID:
    description: 'The client ID for clasp.'
    required: true
  CLASP_CLIENT_SECRET:
    description: 'The client secret for clasp.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    - name: Install clasp and jq
      run: |
        npm install -g @google/clasp
        sudo apt-get update
        sudo apt-get install -y jq
      shell: bash

    - name: Configure clasp credentials
      run: |
        mkdir -p ~/.clasp
        cat <<EOF > ~/.clasprc.json
        {
          "tokens": {
            "default": {
              "client_id": "${{ inputs.CLASP_CLIENT_ID }}",
              "client_secret": "${{ inputs.CLASP_CLIENT_SECRET }}",
              "type": "authorized_user",
              "refresh_token": "${{ inputs.CLASP_REFRESH_TOKEN }}",
              "access_token": "dummy",
              "token_type": "Bearer",
              "expiry_date": 1,
              "id_token": "dummy"
            }
          }
        }
        EOF
      shell: bash

    - name: Generate GAS versions
      run: |
        bash ${{ github.action_path }}/import_gas_versions.sh "${{ inputs.script_id }}" "${{ inputs.author_name }}" "${{ inputs.author_email }}"
      shell: bash

    - name: Push changes
      run: |
        git push
      shell: bash